export const PERMISSIONS = {
  inspection: {
    all: ["can_get_inspection", "can_create_inspection", "can_update_inspection", "can_delete_inspection"],
    getInspection: "can_get_inspection",
    createInspection: "can_create_inspection",
    updateInspection: "can_update_inspection",
    deleteInspection: "can_delete_inspection",
  },
  guarantorTemporaryAddress: {
    all: ["can_create_guarantortemporaryaddress", "can_get_guarantortemporaryaddress", "can_update_guarantortemporaryaddress", "can_delete_guarantortemporaryaddress"],
    createGuarantorTemporaryAddress: "can_create_guarantortemporaryaddress",
    getGuarantorTemporaryAddress: "can_get_guarantortemporaryaddress",
    updateGuarantorTemporaryAddress: "can_update_guarantortemporaryaddress",
    deleteGuarantorTemporaryAddress: "can_delete_guarantortemporaryaddress",
  },
  guarantorPermanentAddress: {
    all: ["can_create_guarantorpermanentaddress", "can_get_guarantorpermanentaddress", "can_update_guarantorpermanentaddress", "can_delete_guarantorpermanentaddress"],
    createGuarantorPermanentAddress: "can_create_guarantorpermanentaddress",
    getGuarantorPermanentAddress: "can_get_guarantorpermanentaddress",
    updateGuarantorPermanentAddress: "can_update_guarantorpermanentaddress",
    deleteGuarantorPermanentAddress: "can_delete_guarantorpermanentaddress",
  },
  guarantor: {
    all: ["can_create_guarantor", "can_get_guarantor", "can_update_guarantor", "can_delete_guarantor"],
    createGuarantor: "can_create_guarantor",
    getGuarantor: "can_get_guarantor",
    updateGuarantor: "can_update_guarantor",
    deleteGuarantor: "can_delete_guarantor",
  },
  facility: {
    all: ["can_create_facility", "can_get_facility", "can_update_facility", "can_delete_facility"],
    createFacility: "can_create_facility",
    getFacility: "can_get_facility",
    updateFacility: "can_update_facility",
    deleteFacility: "can_delete_facility",
  },
  collateralType: {
    all: ["can_create_collateral_type", "can_get_collateral_type", "can_update_collateral_type", "can_delete_collateral_type"],
    createCollateralType: "can_create_collateral_type",
    getCollateralType: "can_get_collateral_type",
    updateCollateralType: "can_update_collateral_type",
    deleteCollateralType: "can_delete_collateral_type",
  },
  collateral: {
    all: ["can_create_collateral", "can_get_collateral", "can_update_collateral", "can_delete_collateral"],
    createCollateral: "can_create_collateral",
    getCollateral: "can_get_collateral",
    updateCollateral: "can_update_collateral",
    deleteCollateral: "can_delete_collateral",
  },
  bsir: {
    all: ["can_create_bsir", "can_get_bsir", "can_update_bsir", "can_delete_bsir"],
    createBsir: "can_create_bsir",
    getBsir: "can_get_bsir",
    updateBsir: "can_update_bsir",
    deleteBsir: "can_delete_bsir",
  },
  recoveryCollectionLoan: {
    all: ["can_create_recoverycollectionloan", "can_get_recoverycollectionloan", "can_update_recoverycollectionloan", "can_delete_recoverycollectionloan"],
    createRecoveryCollectionLoan: "can_create_recoverycollectionloan",
    getRecoveryCollectionLoan: "can_get_recoverycollectionloan",
    updateRecoveryCollectionLoan: "can_update_recoverycollectionloan",
    deleteRecoveryCollectionLoan: "can_delete_recoverycollectionloan",
  },
  recoveryHistory: {
    all: ["can_create_recoveryhistory", "can_get_recoveryhistory", "can_update_recoveryhistory", "can_delete_recoveryhistory"],
    createRecoveryHistory: "can_create_recoveryhistory",
    getRecoveryHistory: "can_get_recoveryhistory",
    updateRecoveryHistory: "can_update_recoveryhistory",
    deleteRecoveryHistory: "can_delete_recoveryhistory",
  },
  newInspectionReports: {
    all: [
      "can_create_newinspectionreports",
      "can_get_newinspectionreports",
      "can_update_newinspectionreports",
      "can_delete_newinspectionreports",
      "can_approve_newinspectionreports",
    ],
    createNewInspectionReports: "can_create_newinspectionreports",
    getNewInspectionReports: "can_get_newinspectionreports",
    updateNewInspectionReports: "can_update_newinspectionreports",
    deleteNewInspectionReports: "can_delete_newinspectionreports",
    approveNewInspectionReports: "can_approve_newinspectionreports",
  },
  businessInspection: {
    all: ["can_create_businessinspection", "can_get_businessinspection", "can_update_businessinspection", "can_delete_businessinspection", "can_approve_businessinspection"],
    createBusinessInspection: "can_create_businessinspection",
    getBusinessInspection: "can_get_businessinspection",
    updateBusinessInspection: "can_update_businessinspection",
    deleteBusinessInspection: "can_delete_businessinspection",
    approveBusinessInspection: "can_approve_businessinspection",
  },
  annex: {
    all: ["can_create_annex", "can_get_annex", "can_update_annex", "can_delete_annex"],
    createAnnex: "can_create_annex",
    getAnnex: "can_get_annex",
    updateAnnex: "can_update_annex",
    deleteAnnex: "can_delete_annex",
  },
  question: {
    all: ["can_create_question", "can_get_question", "can_update_question", "can_delete_question"],
    createQuestion: "can_create_question",
    getQuestion: "can_get_question",
    updateQuestion: "can_update_question",
    deleteQuestion: "can_delete_question",
  },
  answer: {
    all: ["can_create_answer", "can_get_answer", "can_update_answer", "can_delete_answer"],
    createAnswer: "can_create_answer",
    getAnswer: "can_get_answer",
    updateAnswer: "can_update_answer",
    deleteAnswer: "can_delete_answer",
  },
  businessAnswer: {
    all: ["can_create_businessanswer", "can_get_businessanswer", "can_update_businessanswer", "can_delete_businessanswer"],
    createBusinessAnswer: "can_create_businessanswer",
    getBusinessAnswer: "can_get_businessanswer",
    updateBusinessAnswer: "can_update_businessanswer",
    deleteBusinessAnswer: "can_delete_businessanswer",
  },
  businessInspectionAnnexure: {
    all: ["can_create_businessinspectionannexure", "can_get_businessinspectionannexure", "can_update_businessinspectionannexure", "can_delete_businessinspectionannexure"],
    createBusinessInspectionAnnexure: "can_create_businessinspectionannexure",
    getBusinessInspectionAnnexure: "can_get_businessinspectionannexure",
    updateBusinessInspectionAnnexure: "can_update_businessinspectionannexure",
    deleteBusinessInspectionAnnexure: "can_delete_businessinspectionannexure",
  },
  user: {
    all: ["can_create_user", "can_get_user", "can_update_user", "can_delete_user"],
    createUser: "can_create_user",
    getUser: "can_get_user",
    updateUser: "can_update_user",
    deleteUser: "can_delete_user",
  },
  eventLog: {
    all: ["can_create_eventlog", "can_get_eventlog", "can_update_eventlog", "can_delete_eventlog"],
    createEventLog: "can_create_eventlog",
    getEventLog: "can_get_eventlog",
    updateEventLog: "can_update_eventlog",
    deleteEventLog: "can_delete_eventlog",
  },
  fiscalSessionAD: {
    all: ["can_create_fiscalsessionad", "can_get_fiscalsessionad", "can_update_fiscalsessionad", "can_delete_fiscalsessionad"],
    createFiscalSessionAD: "can_create_fiscalsessionad",
    getFiscalSessionAD: "can_get_fiscalsessionad",
    updateFiscalSessionAD: "can_update_fiscalsessionad",
    deleteFiscalSessionAD: "can_delete_fiscalsessionad",
  },
  fiscalSessionBS: {
    all: ["can_create_fiscalsessionbs", "can_get_fiscalsessionbs", "can_update_fiscalsessionbs", "can_delete_fiscalsessionbs"],
    createFiscalSessionBS: "can_create_fiscalsessionbs",
    getFiscalSessionBS: "can_get_fiscalsessionbs",
    updateFiscalSessionBS: "can_update_fiscalsessionbs",
    deleteFiscalSessionBS: "can_delete_fiscalsessionbs",
  },
  country: {
    all: ["can_create_country", "can_get_country", "can_update_country", "can_delete_country"],
    createCountry: "can_create_country",
    getCountry: "can_get_country",
    updateCountry: "can_update_country",
    deleteCountry: "can_delete_country",
  },
  currency: {
    all: ["can_create_currency", "can_get_currency", "can_update_currency", "can_delete_currency"],
    createCurrency: "can_create_currency",
    getCurrency: "can_get_currency",
    updateCurrency: "can_update_currency",
    deleteCurrency: "can_delete_currency",
  },
  organizationSetup: {
    all: ["can_create_organizationsetup", "can_get_organizationsetup", "can_update_organizationsetup", "can_delete_organizationsetup"],
    createOrganizationSetup: "can_create_organizationsetup",
    getOrganizationSetup: "can_get_organizationsetup",
    updateOrganizationSetup: "can_update_organizationsetup",
    deleteOrganizationSetup: "can_delete_organizationsetup",
  },
  province: {
    all: ["can_create_province", "can_get_province", "can_update_province", "can_delete_province"],
    createProvince: "can_create_province",
    getProvince: "can_get_province",
    updateProvince: "can_update_province",
    deleteProvince: "can_delete_province",
  },
  district: {
    all: ["can_create_district", "can_get_district", "can_update_district", "can_delete_district"],
    createDistrict: "can_create_district",
    getDistrict: "can_get_district",
    updateDistrict: "can_update_district",
    deleteDistrict: "can_delete_district",
  },
  palika: {
    all: ["can_create_palika", "can_get_palika", "can_update_palika", "can_delete_palika"],
    createPalika: "can_create_palika",
    getPalika: "can_get_palika",
    updatePalika: "can_update_palika",
    deletePalika: "can_delete_palika",
  },
  organizationHierarchy: {
    all: ["can_create_organizationhierarchy", "can_get_organizationhierarchy", "can_update_organizationhierarchy", "can_delete_organizationhierarchy"],
    createOrganizationHierarchy: "can_create_organizationhierarchy",
    getOrganizationHierarchy: "can_get_organizationhierarchy",
    updateOrganizationHierarchy: "can_update_organizationhierarchy",
    deleteOrganizationHierarchy: "can_delete_organizationhierarchy",
  },
  facilityType: {
    all: ["can_create_facility_type", "can_get_facility_type", "can_update_facility_type", "can_delete_facility_type"],
    createFacilityType: "can_create_facility_type",
    getFacilityType: "can_get_facility_type",
    updateFacilityType: "can_update_facility_type",
    deleteFacilityType: "can_delete_facility_type",
  },
  loanLead: {
    all: ["can_create_loanlead", "can_get_loanlead", "can_update_loanlead", "can_delete_loanlead"],
    createLoanLead: "can_create_loanlead",
    getLoanLead: "can_get_loanlead",
    updateLoanLead: "can_update_loanlead",
    deleteLoanLead: "can_delete_loanlead",
  },
  loanInfo: {
    all: ["can_create_loaninfo", "can_get_loaninfo", "can_update_loaninfo", "can_delete_loaninfo"],
    createLoanInfo: "can_create_loaninfo",
    getLoanInfo: "can_get_loaninfo",
    updateLoanInfo: "can_update_loaninfo",
    deleteLoanInfo: "can_delete_loaninfo",
  },
  guarantorAddress: {
    all: ["can_create_guarantoraddress", "can_get_guarantoraddress", "can_update_guarantoraddress", "can_delete_guarantoraddress"],
    createGuarantorAddress: "can_create_guarantoraddress",
    getGuarantorAddress: "can_get_guarantoraddress",
    updateGuarantorAddress: "can_update_guarantoraddress",
    deleteGuarantorAddress: "can_delete_guarantoraddress",
  },
  guarantorPersonalInfo: {
    all: ["can_create_guarantorpersonalinfo", "can_get_guarantorpersonalinfo", "can_update_guarantorpersonalinfo", "can_delete_guarantorpersonalinfo"],
    createGuarantorPersonalInfo: "can_create_guarantorpersonalinfo",
    getGuarantorPersonalInfo: "can_get_guarantorpersonalinfo",
    updateGuarantorPersonalInfo: "can_update_guarantorpersonalinfo",
    deleteGuarantorPersonalInfo: "can_delete_guarantorpersonalinfo",
  },
  department: {
    all: ["can_create_department", "can_get_department", "can_update_department", "can_delete_department"],
    createDepartment: "can_create_department",
    getDepartment: "can_get_department",
    updateDepartment: "can_update_department",
    deleteDepartment: "can_delete_department",
  },
  scheduleTimeInspection: {
    all: ["can_create_scheduletimeinspection", "can_get_scheduletimeinspection", "can_update_scheduletimeinspection", "can_delete_scheduletimeinspection"],
    createScheduleTimeInspection: "can_create_scheduletimeinspection",
    getScheduleTimeInspection: "can_get_scheduletimeinspection",
    updateScheduleTimeInspection: "can_update_scheduletimeinspection",
    deleteScheduleTimeInspection: "can_delete_scheduletimeinspection",
  },
  userBranch: {
    all: ["can_create_userbranch", "can_get_userbranch", "can_update_userbranch", "can_delete_userbranch"],
    createUserBranch: "can_create_userbranch",
    getUserBranch: "can_get_userbranch",
    updateUserBranch: "can_update_userbranch",
    deleteUserBranch: "can_delete_userbranch",
  },
  employeeHierarchy: {
    all: ["can_create_employeehierarchy", "can_get_employeehierarchy", "can_update_employeehierarchy", "can_delete_employeehierarchy"],
    createEmployeeHierarchy: "can_create_employeehierarchy",
    getEmployeeHierarchy: "can_get_employeehierarchy",
    updateEmployeeHierarchy: "can_update_employeehierarchy",
    deleteEmployeeHierarchy: "can_delete_employeehierarchy",
  },
  userOTPVerification: {
    all: ["can_create_userotpverification", "can_get_userotpverification", "can_update_userotpverification", "can_delete_userotpverification"],
    createUserOTPVerification: "can_create_userotpverification",
    getUserOTPVerification: "can_get_userotpverification",
    updateUserOTPVerification: "can_update_userotpverification",
    deleteUserOTPVerification: "can_delete_userotpverification",
  },
  bankRelations: {
    all: ["can_create_bankrelations", "can_get_bankrelations", "can_update_bankrelations", "can_delete_bankrelations"],
    createBankRelations: "can_create_bankrelations",
    getBankRelations: "can_get_bankrelations",
    updateBankRelations: "can_update_bankrelations",
    deleteBankRelations: "can_delete_bankrelations",
  },
  sisterConcerns: {
    all: ["can_create_sisterconcerns", "can_get_sisterconcerns", "can_update_sisterconcerns", "can_delete_sisterconcerns"],
    createSisterConcerns: "can_create_sisterconcerns",
    getSisterConcerns: "can_get_sisterconcerns",
    updateSisterConcerns: "can_update_sisterconcerns",
    deleteSisterConcerns: "can_delete_sisterconcerns",
  },
  shareHolderDetails: {
    all: ["can_create_shareholderdetails", "can_get_shareholderdetails", "can_update_shareholderdetails", "can_delete_shareholderdetails"],
    createShareHolderDetails: "can_create_shareholderdetails",
    getShareHolderDetails: "can_get_shareholderdetails",
    updateShareHolderDetails: "can_update_shareholderdetails",
    deleteShareHolderDetails: "can_delete_shareholderdetails",
  },
  userGroup: {
    all: ["can_create_customgroup", "can_get_customgroup", "can_update_customgroup", "can_delete_customgroup"],
    createCustomGroup: "can_create_customgroup",
    getCustomGroup: "can_get_customgroup",
    updateCustomGroup: "can_update_customgroup",
    deleteCustomGroup: "can_delete_customgroup",
  },
  permission: {
    all: ["can_create_custompermission", "can_get_custompermission", "can_update_custompermission", "can_delete_custompermission"],
    createCustomPermission: "can_create_custompermission",
    getCustomPermission: "can_get_custompermission",
    updateCustomPermission: "can_update_custompermission",
    deleteCustomPermission: "can_delete_custompermission",
  },
  systemActivity: {
    all: ["can_create_eventlog", "can_get_eventlog", "can_update_eventlog", "can_delete_eventlog"],
    createEventLog: "can_create_eventlog",
    getEventLog: "can_get_eventlog",
    updateEventLog: "can_update_eventlog",
    deleteEventLog: "can_delete_eventlog",
  },
};
